export const TOGGLE_BACKGROUND_COLOR = "TOGGLE_BACKGROUND_COLOR";
export const BOOKING_DATES = "BOOKING_DATES";
export const GUESTS_LIST_INCREMENT = "GUESTS_LIST_INCREMENT";
export const GUESTS_LIST_DECREMENT = "GUESTS_LIST_DECREMENT";
export const DESTINATION_SEARCH = "DESTINATION_SEARCH";
export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const GET_HOTELS = "GET_HOTELS";
