import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import { FC, useEffect, useState } from "react";
import LargeCard from "@/components/LargeCard/LargeCard";
import { useSelector } from "react-redux";
import { getData } from "@/helper/helper";
import TopCarouselNav from "@/components/TopCarouselNav/TopCarouselNav";

const inter = Inter({ subsets: ["latin"] });
interface Iprops {
  smallCardData: any[];
  mediumCardData: any[];
  BaseBannerData: {
    image: string;
    description: string;
    title: string;
  };
  largeCardData: any[];
}

const Home: FC<Iprops> = (props) => {
  const { largeCardData } = props;
  const [scrollActive, setScrollActive] = useState<boolean>(false);

  const style = useSelector((state: any) => state.Reducer);

  useEffect(() => {
    const scrollHandler = () => {
      if (window.scrollY) {
        setScrollActive(true);
      } else {
        setScrollActive(false);
      }
    };
    window.addEventListener("scroll", scrollHandler);
    return () => {
      window.removeEventListener("scroll", scrollHandler);
    };
  }, []);
  return (
    <div className="relative">
      <Head>
        <title>AirBnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white w-[100%] z-20 ">
        <div className="py-4 border-b border-gray-200 w-[100%]">
          <Header />
        </div>
        <div className="w-[100%] my-8">
          <TopCarouselNav />
        </div>
      </div>

      <div className="">
        <LargeCard data={largeCardData} />
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const hotelData: any = getData(
    "https://airbus-demo-1a4fb-default-rtdb.firebaseio.com/hotel.json"
  );

  const data = [];
  for (const key in hotelData) {
    data.push({ id: key, ...hotelData[key] });
  }
  return {
    props: {
      largeCardData: data,
    },
    revalidate: 1,
  };
}

export default Home;
