import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import Banner from "@/components/Banner/Banner";
import { FC } from "react";
import SmallCard from "@/components/SmallCard/SmallCard";
import MediumCard from "@/components/MediumCard/MediumCard";
import LargeCard from "@/components/LargeCard/LargeCard";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
interface Iprops {
  smallCardData: any[];
  mediumCardData: any[];
  BaseBannerData: {
    image: string;
    description: string;
    title: string;
  };
}
const Home: FC<Iprops> = (props) => {
  const { smallCardData, mediumCardData, BaseBannerData } = props;
  console.log(BaseBannerData);
  return (
    <>
      <Head>
        <title>AirBnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore near by</h2>
          <SmallCard country={smallCardData} />
        </section>

        <section className="pt-6">
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <MediumCard data={mediumCardData} />
        </section>
        <section className="pt-6">
          <LargeCard data={BaseBannerData} />
        </section>
      </main>
      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const exploreData = await (
    await fetch(
      "https://airbus-demo-1a4fb-default-rtdb.firebaseio.com/data.json"
    )
  ).json();

  const ExoticHotelsData = await (
    await fetch(
      "https://airbus-demo-1a4fb-default-rtdb.firebaseio.com/exotic.json"
    )
  ).json();

  const BaseBannerData = await (
    await fetch(
      "https://airbus-demo-1a4fb-default-rtdb.firebaseio.com/largeCard.json"
    )
  ).json();
  const smallCardData: any[] = [];
  for (const value in exploreData) {
    smallCardData.push({ id: value, ...exploreData[value] });
  }
  const mediumCardData: any[] = [];
  for (const value in ExoticHotelsData) {
    mediumCardData.push({ id: value, ...ExoticHotelsData[value] });
  }
  return {
    props: {
      smallCardData,
      mediumCardData,
      BaseBannerData: BaseBannerData.l1,
    },
  };
}

export default Home;
